



  logging:
    level:
      org:
        springframework:
          web: DEBUG
          security: DEBUG
          messaging: DEBUG
          websocket: DEBUG

      triolance:
        chat:
          chat_app_backend: DEBUG


  server:
    port: 8080
    servlet:
      context-path: /real-time


  data:
    mongodb:
      host: localhost
      port: 27017
      database: Chat_Application

