

  logging:
    level:
      org:
        springframework:
          security: DEBUG

      triolance:
        chat:
          chat_app_backend: DEBUG


  server:
    port: 8080
    servlet:
      context-path: /real-time


  data:
    mongodb:
      uri: mongodb+srv://monotonousharsh:I2UMWAnU0WXZ8csc@cluster0.ag2sl5g.mongodb.net/Chat_Application?retryWrites=true&w=majority&appName=Cluster0&tls=true&connectTimeoutMS=10000
      database: Chat_Application
      auto-index-creation: true
